//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashRegister.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int LoginId { get; set; }
        public int ClerkId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string OpenedDay { get; set; }
        public string ClosedDay { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<System.DateTime> Since { get; set; }
        public Nullable<System.DateTime> To { get; set; }
    
        public virtual Clerk Clerk { get; set; }
    }
}
